name: Changesets

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  version:
    name: Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: actions/cache@v1
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          commit: 'chore: bump versions'
          title: 'chore: bump versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
